# Generated by Django 4.0 on 2021-12-14 06:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('credit_amount', models.PositiveBigIntegerField()),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('deposit_amount', models.PositiveBigIntegerField()),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('outstanding_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.credit')),
            ],
        ),
    ]
