# Generated by Django 4.0 on 2021-12-15 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='outstanding_credit',
        ),
    ]
